# CircleCI configuration file

version: 2.1
jobs:
  say_hello:
    docker:
      # Primary container image where all steps run
      - image: cimg/base:2022.05
    steps:
      - run echo "Hello world"

  say_goodbye:
    docker:
      - image: cimg/vase:2022.05
    steps:
      - run echo "goodbye from circleci pipeline"

workflows:
  say_hello_and_goodbye:
    jobs:
      - say_hello_and_goodbye/run
      - say_hello
      - say_goodbye
        requires
        - say_hello
